INSERT INTO EMPLOYEE VALUES(
'E1', 'ROHAN',160000,'D1','M1');

INSERT INTO EMPLOYEE VALUES(
'E2', 'RAHUL',170000,'D1','M1');

INSERT INTO EMPLOYEE VALUES(
'E3', 'SHREYA',200000,'D5','M2');

INSERT INTO EMPLOYEE VALUES(
'E4', 'SHRUTI',220000,'D5','M2');

INSERT INTO EMPLOYEE VALUES(
'E5', 'ADITI',290000,'D3','M3');

INSERT INTO EMPLOYEE VALUES(
'E6', 'MEGHNA',295000,'D10','M3');

INSERT INTO MANAGER VALUES(
'M1', 'ROHIT','D3');

INSERT INTO MANAGER VALUES(
'M2', 'NICK','D4');

INSERT INTO MANAGER VALUES(
'M3', 'JAMES','D1');

INSERT INTO MANAGER VALUES(
'M4', 'RITA','D1');

INSERT INTO DEPT VALUES(
'D1','FINANCE' );

INSERT INTO DEPT VALUES(
'D4','IT' );
INSERT INTO DEPT VALUES(
'D3','SALES' );
INSERT INTO DEPT VALUES(
'D5','HR' );

INSERT INTO PROJECTS VALUES(
'P1', 'ETL TOOL','E1');
INSERT INTO PROJECTS VALUES(
'P1', 'ETL TOOL','M4');





