SELECT * FROM EMPLOYEE;
SELECT * FROM MANAGER;
SELECT * FROM DEPT;

SELECT EMP_NAME FROM EMPLOYEE;

SELECT DEPT_ID FROM EMPLOYEE;

SELECT DISTINCT DEPT_ID FROM EMPLOYEE;

SELECT * FROM EMPLOYEE LIMIT 3;

SELECT EMP_NAME, SALARY FROM EMPLOYEE WHERE SALARY>200000;

SELECT * FROM EMPLOYEE WHERE EMP_NAME LIKE 'S%';

SELECT * FROM EMPLOYEE WHERE EMP_NAME LIKE '%A';

SELECT * FROM EMPLOYEE WHERE EMP_NAME LIKE 'R_H%';

SELECT * FROM EMPLOYEE WHERE EMP_NAME LIKE 'R_H%' AND SALARY=170000;

SELECT * FROM EMPLOYEE WHERE EMP_NAME LIKE '%A' OR EMP_NAME LIKE '%S';

SELECT EMP_NAME, SALARY FROM EMPLOYEE ORDER BY SALARY  ;

SELECT * FROM EMPLOYEE WHERE EMP_NAME IN ('SHRUTI','SHREYA', 'VARSHA');

SELECT * FROM EMPLOYEE WHERE SALARY BETWEEN 190000 AND 220000;

SELECT * FROM EMPLOYEE WHERE EMP_NAME BETWEEN 'RAHUL' AND 'SHREYA';

-- Update

SET SQL_SAFE_UPDATES = 0;
Update EMPLOYEE set salary=350000 where EMP_NAME='SHRUTI';
-- Delete 
Delete from Employee where emp_name='Shreya';



