use demodb;
CREATE TABLE USERS(USERNAME VARCHAR(255),U_PASSWORD VARCHAR(255),FNAME VARCHAR(255),LNAME VARCHAR(255));

INSERT INTO USERS VALUES('SHRUTI_M','SHR2002#','SHRUTI','MUNGALE');
INSERT INTO USERS VALUES('ADITI10','AM2000#','ADITI','MUNGALE');
INSERT INTO USERS VALUES('PC02','D#67','PALAK','CHOPRA');
INSERT INTO USERS VALUES('NIYU26','SKPR02','NIYATI','ROLIA');
INSERT INTO USERS VALUES('RIDYA','PYA02','RIDDHI','ARYA');
